# -*- mode: ruby -*-
# vi: set ft=ruby :
machines=[
  {
    :hostname => "clorinS",
    :ip => "192.168.56.110",
    :box => "generic/centos8",
    :ram => 512,
    :cpu => 1
  },
  {
    :hostname => "clorinSW",
    :ip => "192.168.56.111",
    :box => "generic/centos8",
    :ram => 512,
    :cpu => 1
  }
]

Vagrant.configure(2) do |config|
    machines.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip]
            node.vm.provider "virtualbox" do |vb|
                vb.gui = false
                vb.memory = machine[:ram]
                vb.cpus = machine[:cpu]
            end
        end
    end
end
