Vagrant.configure("2") do |config|
    config.vm.box = "generic/centos8"
    config.vm.box_url = "https://app.vagrantup.com/generic/boxes/centos8/versions/4.3.6/providers/virtualbox/amd64/vagrant.box"
    config.vm.box_check_update = false
    # config.vbguest.installer_options = { allow_kernel_upgrade: true }

    #common config
    config.vm.provider "virtualbox" do |v|
        v.gui = false
		v.memory = 512
		v.cpus = 1
		v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
	end

    #config Server
    config.vm.define "clorinS" do |master|
        master.vm.hostname = "clorinS"
        master.vm.network "private_network", type: "static", ip: "192.168.56.110"
        master.vm.synced_folder ".", "/vagrant", type: "virtualbox"
        master.vm.provision "shell", privileged: true, path: "scripts/master_setup.sh", args: "192.168.56.110"

        master.vm.provider "virtualbox" do |vb|
            vb.name = "clorinS"
        end
    end
    #config worker
    config.vm.define "clorinSW" do |worker|
        worker.vm.hostname = "clorinS"
        worker.vm.network "private_network", type: "static", ip: "192.168.56.111"
        worker.vm.synced_folder ".", "/vagrant", type: "virtualbox"
        worker.vm.provision "shell", privileged: true, path: "scripts/worker_setup.sh", args: ["192.168.56.110", "192.168.56.111"]
        worker.vm.provider "virtualbox" do |vb|
            vb.name = "clorinSW"
        end
    end
end